import { PROVIDER_IDS } from "../src/schemas.js";
import { SERVER_NAME, SERVER_VERSION } from "../src/server.js";
import { SITE_URL } from "./site.js";

/**
 * llms.txt / llms-full.txt — the agent-facing instruction documents
 * (llmstxt.org convention). llms.txt is the concise quick-start; the full
 * variant inlines the complete tool/API reference and every provider id.
 */

const MCP_ENDPOINT = `${SITE_URL}/api/mcp`;

export function buildLlmsTxt(): string {
  return [
    `# ${SERVER_NAME}`,
    "",
    `> Check whether a project or brand name is available across domains, developer platforms, package registries and social networks — and score it for brand quality — from the web UI, a JSON API, or any MCP-compatible AI assistant.`,
    "",
    `${SERVER_NAME} runs one candidate name against 55+ independent providers and reports a uniform verdict per provider (available | taken | unknown | invalid) plus a deterministic 0–100 brand score.`,
    "",
    "## When to use this",
    "",
    `- Evaluating a name for a project, product, company, package or handle **before** registering it anywhere.`,
    `- Checking the "does X exist?" question across .com/.dev/.io/.gg, GitHub, npm, PyPI, crates.io, Docker Hub, Vercel/Netlify subdomains, the App Store and social handles in a single call.`,
    `- Comparing candidate names with a deterministic brand score (punchiness, pronounceability, uniqueness, cleanliness) instead of vibes.`,
    `- Not for: trademark/legal clearance, premium-domain pricing, or guaranteed availability — verdicts are best-effort snapshots to re-confirm at the source.`,
    "",
    "## MCP server (recommended for AI assistants)",
    "",
    `- Endpoint: POST ${MCP_ENDPOINT}`,
    `- Transport: Streamable HTTP, stateless — POST JSON-RPC 2.0 with Accept: application/json, text/event-stream`,
    `- Discovery document: GET ${SITE_URL}/.well-known/mcp`,
    `- Tools: check_availability({ name, providers? }) and score_name({ name })`,
    `- Local stdio alternative: npx ${SERVER_NAME} (MCP stdio transport)`,
    "",
    "## HTTP API",
    "",
    `- GET ${SITE_URL}/api/availability?name=<name>[&providers=<csv>] — normalized availability results (aliases: /api/v1/availability, /v1/check)`,
    `- GET ${SITE_URL}/api/score?name=<name> — deterministic brand score (aliases: /api/v1/score, /v1/score)`,
    `- POST ${SITE_URL}/api/mcp — MCP JSON-RPC 2.0 transport (aliases: /api/v1/mcp, /v1/mcp)`,
    `- GET ${SITE_URL}/v1 — API version index (apiVersion, endpoints, deprecation status)`,
    `- GET ${SITE_URL}/api/mcp (also /mcp, /health) — endpoint status`,
    `- GET ${SITE_URL}/openapi.json — OpenAPI 3.1 description of this API`,
    "",
    "## Invocation examples",
    "",
    "```",
    `curl -s '${SITE_URL}/api/v1/availability?name=myapp&providers=domains,github,npm'`,
    `curl -s '${SITE_URL}/api/v1/score?name=myapp'`,
    `curl -s -X POST ${MCP_ENDPOINT} \\`,
    `  -H 'content-type: application/json' \\`,
    `  -H 'accept: application/json, text/event-stream' \\`,
    `  -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"score_name","arguments":{"name":"myapp"}}}'`,
    "```",
    "",
    `No authentication. The API is version 1 — \`/api/v1/*\` is canonical (root-level \`/v1/*\` and unversioned \`/api/*\` are aliases) and every response on every /api/* and /v1/* endpoint carries \`API-Version: 1\`, \`X-API-Version: 1.0.0\` and RFC RateLimit headers (\`RateLimit-Limit\`, \`RateLimit-Remaining\`, \`RateLimit-Reset\`, \`RateLimit-Policy: <limit>;w=60\`) — including errors and 404s; honor \`Retry-After\` on 429. Deprecation policy: a future breaking v2 would keep v1 live and emit \`Deprecation: true\`, \`Sunset\` and a \`Link rel="deprecation"\` pointer for at least 6 months (see /auth.md). Errors are structured: {error:{code,message,hint}}. Send Accept: text/markdown to any page URL to get this site as markdown; Accept: application/json on an unknown URL (including unmapped /api/* and /v1/* paths) yields a JSON 404.`,
    "",
    "## Discovery documents",
    "",
    `- OAuth discovery documents (public/no-token tier): ${SITE_URL}/.well-known/oauth-protected-resource (RFC 9728; .json alias also served) and ${SITE_URL}/.well-known/oauth-authorization-server (RFC 8414)`,
    "",
    `Rate limits and access details: ${SITE_URL}/auth.md`,
    "",
    "## Links",
    "",
    `- [Complete agent instructions](${SITE_URL}/llms-full.txt)`,
    `- [Documentation](${SITE_URL}/docs)`,
    `- [OpenAPI 3.1](${SITE_URL}/openapi.json)`,
    `- [MCP server card (SEP-1649)](${SITE_URL}/.well-known/mcp/server-card.json)`,
    `- [API catalog linkset](${SITE_URL}/.well-known/api-catalog)`,
    `- [AI catalog](${SITE_URL}/.well-known/ai-catalog.json)`,
    `- [Agent skills index](${SITE_URL}/.well-known/agent-skills/index.json)`,
    `- [Authentication & rate limits](${SITE_URL}/auth.md)`,
    "",
    "## Pages",
    "",
    `- [Home](${SITE_URL}/)`,
    `- [Docs](${SITE_URL}/docs)`,
    `- [About](${SITE_URL}/about)`,
    `- [Contact](${SITE_URL}/contact)`,
    `- [Privacy](${SITE_URL}/privacy)`,
    `- [Credits](${SITE_URL}/credits)`,
    `- [sitemap.xml](${SITE_URL}/sitemap.xml)`,
    "",
  ].join("\n");
}

export function buildLlmsFullTxt(): string {
  return [
    buildLlmsTxt().trimEnd(),
    "",
    "---",
    "",
    `# ${SERVER_NAME} — full reference`,
    "",
    `Version ${SERVER_VERSION}. Everything below is callable without authentication.`,
    "",
    "## MCP tools",
    "",
    "### check_availability",
    "",
    "Input: `{ name: string, providers?: string[] }`. `name` is a bare name — 1–63 chars, starts alnum, ASCII letters/digits plus `.`, `_`, `-`. `providers` is an optional list of provider ids or aliases.",
    "",
    "Output: `{ name, results, summary }` where each result is `{ provider, status, subject, available, detail?, durationMs }`; `status` is `available | taken | unknown | invalid` and `available` agrees with it (`unknown` → null). Providers run concurrently with a 5-second timeout each; a failure reports `unknown`, it never fails the batch.",
    "",
    "Provider aliases: `all`, `domains`, `domains:cctld`, `domains:all`, `socials`.",
    "",
    "Handshake — initialize is a plain POST (no session state, no auth):",
    "",
    "```",
    `curl -s -X POST ${MCP_ENDPOINT} \\`,
    `  -H 'content-type: application/json' \\`,
    `  -H 'accept: application/json, text/event-stream' \\`,
    `  -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"my-agent","version":"1.0"}}}'`,
    "```",
    "",
    "Example JSON-RPC tools/call over the hosted endpoint:",
    "",
    "```",
    `curl -s -X POST ${MCP_ENDPOINT} \\`,
    `  -H 'content-type: application/json' \\`,
    `  -H 'accept: application/json, text/event-stream' \\`,
    `  -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"check_availability","arguments":{"name":"myapp","providers":["domains","github","npm"]}}}'`,
    "```",
    "",
    "### score_name",
    "",
    "Input: `{ name: string }` — same validation. Output: deterministic `{ name, total, grade, components }` where `total` is 0–100 and components cover punchiness (length, 5–8 chars optimal), pronounceability (English bigrams, syllable estimate), uniqueness (coinages beat common words) and cleanliness (penalties for digits, separators, repeats). No network — same input, same score.",
    "",
    "## HTTP API",
    "",
    "```",
    `curl -s '${SITE_URL}/api/v1/availability?name=myapp&providers=domains,github,npm'`,
    `curl -s '${SITE_URL}/api/v1/score?name=myapp'`,
    "```",
    "",
    "`GET /api/v1/availability` (or the unversioned `/api/availability` or root `/v1/check` aliases) returns `{ name, results, summary, mode }` (`mode` is `live`, or `demo` when the deployment serves deterministic fixtures). `GET /api/v1/score` (`/v1/score`) returns the score payload. Both return `400` for an invalid name. `GET /v1` returns the version index ({apiVersion, endpoints, deprecated}). Every response on every /api/* and /v1/* endpoint carries `API-Version: 1`, `X-API-Version: 1.0.0` and `RateLimit-Limit`/`RateLimit-Remaining`/`RateLimit-Reset`/`RateLimit-Policy` — including errors and 404s; a `429` comes with `Retry-After` and the same error envelope. Rate limits are applied per client IP; JSON-RPC errors follow the JSON-RPC 2.0 shape.",
    "",
    "## Provider ids",
    "",
    "Valid `providers` entries:",
    "",
    ...PROVIDER_IDS.map((id) => `- ${id}`),
    "",
    "Aliases: `all` (every provider), `domains` (core TLDs), `domains:cctld` (European ccTLDs), `domains:all` (all TLDs), `socials` (social handles).",
    "",
    "## Connecting MCP clients",
    "",
    `- Cursor: add to .cursor/mcp.json → { "mcpServers": { "${SERVER_NAME}": { "url": "${MCP_ENDPOINT}" } } }`,
    `- VS Code: .vscode/mcp.json → { "servers": { "${SERVER_NAME}": { "type": "http", "url": "${MCP_ENDPOINT}" } } }`,
    `- Windsurf: ~/.codeium/windsurf/mcp_config.json → { "mcpServers": { "${SERVER_NAME}": { "serverUrl": "${MCP_ENDPOINT}" } } }`,
    `- Claude Desktop: claude_desktop_config.json → { "mcpServers": { "${SERVER_NAME}": { "command": "npx", "args": ["mcp-remote", "${MCP_ENDPOINT}"] } } }`,
    `- Claude Code: \`claude mcp add --transport http ${SERVER_NAME} ${MCP_ENDPOINT}\``,
    `- Any client: run \`npx ${SERVER_NAME}\` for the stdio transport.`,
    "",
    "## Accuracy",
    "",
    "Verdicts are best-effort snapshots of public registration state. `available` requires a verified unclaimed marker (RDAP/registry 404, WHOIS no-match); `unknown` means the source could not be checked. Always re-confirm at the registrar or platform before purchasing or registering.",
    "",
    `Docs: ${SITE_URL}/docs — how checks run, provider semantics, the HTTP API and the MCP transport.`,
    "",
  ].join("\n");
}
